### ISSUE TITLE
Current peerDependency doesn't match cds 8

### ISSUE THREAD

**Issue by David-Kunz** [cap-js/notifications#57]
The peer dependency of the released package is

```
  "peerDependencies": {
    "@sap/cds": "^7.3.1",
  }
```

which doesn't match our freshly-released @sap/cds 8.

In `main`, it's https://github.com/cap-js/notifications/blob/6f8d9a74469945edfc64b53270f8ab8e1b0903b8/package.json#L15

A release should be triggered, otherwise it cannot be consumed with @sap/cds 8.

**Comment by chgeo** [comment]
@RamIndia can you make sure there is a new release?

**Comment by gregorwolf** [comment]
Any progress @RamIndia ?

**Comment by hschaefer123** [comment]
Also need this! Still waiting for an update by @RamIndia

**Comment by nvvalchev** [comment]
Our team would review and test the change in https://github.com/cap-js/notifications/pull/56  in beginning of next week.

**Comment by gregorwolf** [comment]
Any progress @nvvalchev ?
