### ISSUE TITLE
The cds build plugin 'notifications' is not compatible with this @sap/cds-dk version. Update the npm package '@cap-js/notifications/lib/build' to the latest version.

### ISSUE THREAD

**Issue by gopalanand333** [cap-js/notifications#69]
Hi team, 
With the latest version of notifications plugin, I am getting the following error: 
```
The cds build plugin 'notifications' is not compatible with this @sap/cds-dk version.
 Update the npm package '@cap-js/notifications/lib/build' to the latest version.
```
My cds version is 
| incident-management    | <Add your repository here>                                                                                     |
| ---------------------- | -------------------------------------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                                                          |
| @cap-js/cds-types      | 0.6.5                                                                                                          |
| @cap-js/db-service     | 1.12.0                                                                                                         |
| @cap-js/hana           | 1.2.0                                                                                                          |
| @cap-js/notifications  | 0.2.1                                                                                                          |
| @cap-js/openapi        | 1.0.5                                                                                                          |
| @cap-js/sqlite         | 1.7.3                                                                                                          |
| @sap/cds               | 8.2.1                                                                                                          |
| @sap/cds-compiler      | 5.1.2                                                                                                          |
| @sap/cds-dk            | 8.2.0                                                                                                          |
| @sap/cds-dk (global)   | 8.2.0                                                                                                          |
| @sap/cds-fiori         | 1.2.7                                                                                                          |
| @sap/cds-foss          | 5.0.1                                                                                                          |
| @sap/cds-mtxs          | 2.1.0                                                                                                          |
| @sap/eslint-plugin-cds | 3.0.4                                                                                                          |
| Node.js                | v20.16.0                                                                                                       |

**Comment by hschaefer123** [comment]
Same for me!

**Comment by VanitaDhanagar** [comment]
same error [2024-09-18 04:25:39]  The cds build plugin 'notifications' is not compatible with this @sap/cds-dk version. Update the npm package '@cap-js/notifications/lib/build' to the latest version.
